name: youtube_podcast
description: Youtube Podcast.

# Prevent accidental publishing to pub.dev.
publish_to: 'none'

version: 1.0.0+1

# TODO: Update Dart (and Flutter) to version 3 once it's released (soon I guess?).
environment:
  sdk: '>=2.19.0 <3.0.0'

dependencies:
  cached_network_image: ^3.2.3
  collection: ^1.16.0
  crypto: ^3.0.2
  device_info_plus: ^8.0.0
  flutter:
    sdk: flutter
  flutter_dotenv: ^5.0.2
  flutter_downloader: ^1.10.1
  flutter_easyloading: ^3.0.5
  flutter_launcher_icons: ^0.11.0
  flutter_linkify: ^5.0.2
  flutter_localizations:
    sdk: flutter
  flutter_native_splash: ^2.2.16
  get_it: ^7.2.0
  http: ^0.13.5
  like_button: ^2.0.5
  open_filex: ^4.3.2
  path: ^1.8.2
  permission_handler: ^10.2.0
  provider: ^6.0.5
  shared_preferences: ^2.0.16
  socket_io_client: ^2.0.1
  url_launcher: ^6.1.7

dev_dependencies:
  flutter_test:
    sdk: flutter
  mockito: ^5.4.0

  flutter_lints: ^2.0.0
  test: ^1.22.0
  build_runner: ^2.3.3

flutter:
  uses-material-design: true

  fonts:
  - family: WorkSans
    fonts:
      - asset: assets/fonts/WorkSans-VariableFont_wght.ttf
      - asset: assets/fonts/WorkSans-Italic-VariableFont_wght.ttf
        style: italic

  # Enable generation of localized Strings from arb files.
  generate: true

  assets:
    - assets/.env.development
    - assets/.env.production
    - assets/.env.emulator
    # Add assets from the images directory to the application.
    - assets/images/
    - assets/fonts/
